# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymail.ui'
#
# Created: Wed Oct 26 00:02:40 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 421)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.head_label_1 = QtGui.QLabel(self.centralwidget)
        self.head_label_1.setGeometry(QtCore.QRect(490, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.head_label_1.setFont(font)
        self.head_label_1.setObjectName("head_label_1")
        self.pop_host = QtGui.QLabel(self.centralwidget)
        self.pop_host.setGeometry(QtCore.QRect(420, 240, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pop_host.setFont(font)
        self.pop_host.setObjectName("pop_host")
        self.pop_host_value = QtGui.QLineEdit(self.centralwidget)
        self.pop_host_value.setGeometry(QtCore.QRect(520, 240, 201, 32))
        self.pop_host_value.setObjectName("pop_host_value")
        self.pop_port = QtGui.QLabel(self.centralwidget)
        self.pop_port.setGeometry(QtCore.QRect(420, 280, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pop_port.setFont(font)
        self.pop_port.setObjectName("pop_port")
        self.pass_text = QtGui.QLineEdit(self.centralwidget)
        self.pass_text.setGeometry(QtCore.QRect(150, 210, 201, 32))
        self.pass_text.setObjectName("pass_text")
        self.smtp_host = QtGui.QLabel(self.centralwidget)
        self.smtp_host.setGeometry(QtCore.QRect(420, 110, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.smtp_host.setFont(font)
        self.smtp_host.setObjectName("smtp_host")
        self.smtp_host_value = QtGui.QLineEdit(self.centralwidget)
        self.smtp_host_value.setGeometry(QtCore.QRect(520, 110, 201, 32))
        self.smtp_host_value.setObjectName("smtp_host_value")
        self.head_label_2 = QtGui.QLabel(self.centralwidget)
        self.head_label_2.setGeometry(QtCore.QRect(490, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.head_label_2.setFont(font)
        self.head_label_2.setObjectName("head_label_2")
        self.login_status = QtGui.QLabel(self.centralwidget)
        self.login_status.setGeometry(QtCore.QRect(90, 120, 241, 17))
        self.login_status.setText("")
        self.login_status.setObjectName("login_status")
        self.smtp_port = QtGui.QLabel(self.centralwidget)
        self.smtp_port.setGeometry(QtCore.QRect(420, 150, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.smtp_port.setFont(font)
        self.smtp_port.setObjectName("smtp_port")
        self.user_text = QtGui.QLineEdit(self.centralwidget)
        self.user_text.setGeometry(QtCore.QRect(150, 160, 201, 32))
        self.user_text.setObjectName("user_text")
        self.app_title = QtGui.QLabel(self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(140, 60, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.app_title.setFont(font)
        self.app_title.setObjectName("app_title")
        self.user_label = QtGui.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(40, 160, 101, 21))
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(14)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.smtp_port_value = QtGui.QLineEdit(self.centralwidget)
        self.smtp_port_value.setGeometry(QtCore.QRect(520, 150, 201, 32))
        self.smtp_port_value.setObjectName("smtp_port_value")
        self.pop_port_value = QtGui.QLineEdit(self.centralwidget)
        self.pop_port_value.setGeometry(QtCore.QRect(520, 280, 201, 32))
        self.pop_port_value.setObjectName("pop_port_value")
        self.pass_label = QtGui.QLabel(self.centralwidget)
        self.pass_label.setGeometry(QtCore.QRect(40, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(14)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.login_button = QtGui.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(150, 270, 92, 33))
        self.login_button.setObjectName("login_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSMTP_Host = QtGui.QAction(MainWindow)
        self.actionSMTP_Host.setObjectName("actionSMTP_Host")
        self.actionSMTP_Port = QtGui.QAction(MainWindow)
        self.actionSMTP_Port.setObjectName("actionSMTP_Port")
        self.actionPOP3_Host = QtGui.QAction(MainWindow)
        self.actionPOP3_Host.setObjectName("actionPOP3_Host")
        self.actionPOP3_Port = QtGui.QAction(MainWindow)
        self.actionPOP3_Port.setObjectName("actionPOP3_Port")
        self.actionRetrieve_Mails = QtGui.QAction(MainWindow)
        self.actionRetrieve_Mails.setObjectName("actionRetrieve_Mails")
        self.actionCompose = QtGui.QAction(MainWindow)
        self.actionCompose.setObjectName("actionCompose")
        self.actionCreated_By = QtGui.QAction(MainWindow)
        self.actionCreated_By.setObjectName("actionCreated_By")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.head_label_1.setText(QtGui.QApplication.translate("MainWindow", "POP3 Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pop_host.setText(QtGui.QApplication.translate("MainWindow", "POP3 Host", None, QtGui.QApplication.UnicodeUTF8))
        self.pop_port.setText(QtGui.QApplication.translate("MainWindow", "POP3 Port", None, QtGui.QApplication.UnicodeUTF8))
        self.smtp_host.setText(QtGui.QApplication.translate("MainWindow", "SMTP Host", None, QtGui.QApplication.UnicodeUTF8))
        self.head_label_2.setText(QtGui.QApplication.translate("MainWindow", "SMTP Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.smtp_port.setText(QtGui.QApplication.translate("MainWindow", "SMTP Port", None, QtGui.QApplication.UnicodeUTF8))
        self.app_title.setText(QtGui.QApplication.translate("MainWindow", "PyMail", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.pass_label.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.login_button.setText(QtGui.QApplication.translate("MainWindow", "LOGIN", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSMTP_Host.setText(QtGui.QApplication.translate("MainWindow", "SMTP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSMTP_Port.setText(QtGui.QApplication.translate("MainWindow", "SMTP Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPOP3_Host.setText(QtGui.QApplication.translate("MainWindow", "POP3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPOP3_Port.setText(QtGui.QApplication.translate("MainWindow", "POP3 Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRetrieve_Mails.setText(QtGui.QApplication.translate("MainWindow", "Retrieve Mails", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompose.setText(QtGui.QApplication.translate("MainWindow", "Compose", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreated_By.setText(QtGui.QApplication.translate("MainWindow", "Created By", None, QtGui.QApplication.UnicodeUTF8))

