# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/mainwindow.ui'
#
# Created: Wed Oct 26 03:38:40 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1263, 531)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.head_label_1 = QtGui.QLabel(self.centralwidget)
        self.head_label_1.setGeometry(QtCore.QRect(530, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.head_label_1.setFont(font)
        self.head_label_1.setObjectName("head_label_1")
        self.pop_host = QtGui.QLabel(self.centralwidget)
        self.pop_host.setGeometry(QtCore.QRect(470, 330, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pop_host.setFont(font)
        self.pop_host.setObjectName("pop_host")
        self.pop_host_value = QtGui.QLineEdit(self.centralwidget)
        self.pop_host_value.setGeometry(QtCore.QRect(570, 330, 201, 32))
        self.pop_host_value.setObjectName("pop_host_value")
        self.pop_port = QtGui.QLabel(self.centralwidget)
        self.pop_port.setGeometry(QtCore.QRect(470, 370, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pop_port.setFont(font)
        self.pop_port.setObjectName("pop_port")
        self.pass_text = QtGui.QLineEdit(self.centralwidget)
        self.pass_text.setGeometry(QtCore.QRect(560, 120, 201, 41))
        self.pass_text.setObjectName("pass_text")
        self.smtp_host = QtGui.QLabel(self.centralwidget)
        self.smtp_host.setGeometry(QtCore.QRect(50, 330, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.smtp_host.setFont(font)
        self.smtp_host.setObjectName("smtp_host")
        self.smtp_host_value = QtGui.QLineEdit(self.centralwidget)
        self.smtp_host_value.setGeometry(QtCore.QRect(150, 330, 201, 32))
        self.smtp_host_value.setObjectName("smtp_host_value")
        self.head_label_2 = QtGui.QLabel(self.centralwidget)
        self.head_label_2.setGeometry(QtCore.QRect(120, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.head_label_2.setFont(font)
        self.head_label_2.setObjectName("head_label_2")
        self.login_status = QtGui.QLabel(self.centralwidget)
        self.login_status.setGeometry(QtCore.QRect(520, 60, 241, 17))
        self.login_status.setText("")
        self.login_status.setOpenExternalLinks(False)
        self.login_status.setObjectName("login_status")
        self.smtp_port = QtGui.QLabel(self.centralwidget)
        self.smtp_port.setGeometry(QtCore.QRect(50, 370, 91, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.smtp_port.setFont(font)
        self.smtp_port.setObjectName("smtp_port")
        self.user_text = QtGui.QLineEdit(self.centralwidget)
        self.user_text.setGeometry(QtCore.QRect(560, 71, 201, 41))
        self.user_text.setObjectName("user_text")
        self.app_title = QtGui.QLabel(self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(580, 0, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.app_title.setFont(font)
        self.app_title.setObjectName("app_title")
        self.user_label = QtGui.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(450, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(14)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.smtp_port_value = QtGui.QLineEdit(self.centralwidget)
        self.smtp_port_value.setGeometry(QtCore.QRect(150, 370, 201, 32))
        self.smtp_port_value.setObjectName("smtp_port_value")
        self.pop_port_value = QtGui.QLineEdit(self.centralwidget)
        self.pop_port_value.setGeometry(QtCore.QRect(570, 370, 201, 32))
        self.pop_port_value.setObjectName("pop_port_value")
        self.pass_label = QtGui.QLabel(self.centralwidget)
        self.pass_label.setGeometry(QtCore.QRect(450, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(14)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.login_button = QtGui.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(600, 180, 92, 33))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(940, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1040, 330, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(940, 390, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1040, 390, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(940, 430, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1040, 430, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1040, 350, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(940, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1040, 410, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(940, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1040, 370, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(940, 370, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.head_label_3 = QtGui.QLabel(self.centralwidget)
        self.head_label_3.setGeometry(QtCore.QRect(960, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.head_label_3.setFont(font)
        self.head_label_3.setObjectName("head_label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSMTP_Host = QtGui.QAction(MainWindow)
        self.actionSMTP_Host.setObjectName("actionSMTP_Host")
        self.actionSMTP_Port = QtGui.QAction(MainWindow)
        self.actionSMTP_Port.setObjectName("actionSMTP_Port")
        self.actionPOP3_Host = QtGui.QAction(MainWindow)
        self.actionPOP3_Host.setObjectName("actionPOP3_Host")
        self.actionPOP3_Port = QtGui.QAction(MainWindow)
        self.actionPOP3_Port.setObjectName("actionPOP3_Port")
        self.actionRetrieve_Mails = QtGui.QAction(MainWindow)
        self.actionRetrieve_Mails.setObjectName("actionRetrieve_Mails")
        self.actionCompose = QtGui.QAction(MainWindow)
        self.actionCompose.setObjectName("actionCompose")
        self.actionCreated_By = QtGui.QAction(MainWindow)
        self.actionCreated_By.setObjectName("actionCreated_By")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.head_label_1.setText(QtGui.QApplication.translate("MainWindow", "POP3 Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pop_host.setText(QtGui.QApplication.translate("MainWindow", "POP3 Host", None, QtGui.QApplication.UnicodeUTF8))
        self.pop_port.setText(QtGui.QApplication.translate("MainWindow", "POP3 Port", None, QtGui.QApplication.UnicodeUTF8))
        self.smtp_host.setText(QtGui.QApplication.translate("MainWindow", "SMTP Host", None, QtGui.QApplication.UnicodeUTF8))
        self.head_label_2.setText(QtGui.QApplication.translate("MainWindow", "SMTP Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.smtp_port.setText(QtGui.QApplication.translate("MainWindow", "SMTP Port", None, QtGui.QApplication.UnicodeUTF8))
        self.app_title.setText(QtGui.QApplication.translate("MainWindow", "PyMail", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.pass_label.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.login_button.setText(QtGui.QApplication.translate("MainWindow", "LOGIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "14114013", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Anshul Shah", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "14114028", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Harkirat Singh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "14114030", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Ketan Mittal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Nikhil Sheoran", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "14114031", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Prashant Kumar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "14114037", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Pratyush Rajput", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "14114039", None, QtGui.QApplication.UnicodeUTF8))
        self.head_label_3.setText(QtGui.QApplication.translate("MainWindow", "Created By", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSMTP_Host.setText(QtGui.QApplication.translate("MainWindow", "SMTP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSMTP_Port.setText(QtGui.QApplication.translate("MainWindow", "SMTP Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPOP3_Host.setText(QtGui.QApplication.translate("MainWindow", "POP3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPOP3_Port.setText(QtGui.QApplication.translate("MainWindow", "POP3 Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRetrieve_Mails.setText(QtGui.QApplication.translate("MainWindow", "Retrieve Mails", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompose.setText(QtGui.QApplication.translate("MainWindow", "Compose", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreated_By.setText(QtGui.QApplication.translate("MainWindow", "Created By", None, QtGui.QApplication.UnicodeUTF8))

